volumes:
  configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Solution Items

services:
  nephele.botmanager.api:
    image: ${DOCKER_REGISTRY-}nephele.botmanager.api
    container_name: nephele.botmanager.api
